language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

script: phpunit --bootstrap "phpunit_bootstrap.php" --no-configuration
